spring.application.name=clinica-gastro

server.servlet.context-path=/clinica-gastro

spring.datasource.url=jdbc:postgresql://localhost:5432/teste4
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver




# Mostra o SQL com ? (placeholders)
spring.jpa.show-sql=true

# Mostra os valores reais dos parâmetros SQL
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type.descriptor.sql.BasicBinder.log=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE


server.error.include-stacktrace=never

