spring.application.name=clinica-gastro

server.servlet.context-path=/clinica-gastro

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/teste4}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${SERVER_PORT:8080}

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type.descriptor.sql.BasicBinder.log=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
#teste
server.error.include-stacktrace=never